// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgC6gy6uTTgJ95Av6b-bS8wJDIVJhj3pE',
    appId: '1:612053474164:web:a178a590aea8beb8b12a21',
    messagingSenderId: '612053474164',
    projectId: 'aquasmatters',
    authDomain: 'aquasmatters.firebaseapp.com',
    databaseURL: 'https://aquasmatters-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aquasmatters.firebasestorage.app',
    measurementId: 'G-1LCKCEDC9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqxue260fXY4yY3fpPAL11QHHcp7AqpBs',
    appId: '1:612053474164:android:bdd808545dff00e2b12a21',
    messagingSenderId: '612053474164',
    projectId: 'aquasmatters',
    databaseURL: 'https://aquasmatters-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aquasmatters.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz1AWtoOqQ3BmYS1lqrPpWO71U31H3BVA',
    appId: '1:612053474164:ios:066f8f210714ac6db12a21',
    messagingSenderId: '612053474164',
    projectId: 'aquasmatters',
    databaseURL: 'https://aquasmatters-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aquasmatters.firebasestorage.app',
    iosBundleId: 'com.example.aquaSmatters',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz1AWtoOqQ3BmYS1lqrPpWO71U31H3BVA',
    appId: '1:612053474164:ios:066f8f210714ac6db12a21',
    messagingSenderId: '612053474164',
    projectId: 'aquasmatters',
    databaseURL: 'https://aquasmatters-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aquasmatters.firebasestorage.app',
    iosBundleId: 'com.example.aquaSmatters',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgC6gy6uTTgJ95Av6b-bS8wJDIVJhj3pE',
    appId: '1:612053474164:web:fe6c90d2ee76d19ab12a21',
    messagingSenderId: '612053474164',
    projectId: 'aquasmatters',
    authDomain: 'aquasmatters.firebaseapp.com',
    databaseURL: 'https://aquasmatters-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aquasmatters.firebasestorage.app',
    measurementId: 'G-64L4X6K5QE',
  );
}
